[package]
name = "rtar"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS tar module"
license = "MIT"

[dependencies]
vantara = { path = "../../../" }
tar = "0.4"
flate2 = "1.0"
bzip2 = "0.6.0"
xz2 = "0.1"
anyhow = "1.0"
