[package]
name = "whoami"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS whoami module"
license = "Apache-2.0 license"

[dependencies]
vantara = { path = "../../../" }