[package]
name = "find"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS find module"
license = "MIT"

[dependencies]
walkdir = "2"
glob = "0.3"
vantara = { path = "../../../" }
