[package]
name = "chmod"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS chmod module"
license = "Apache-2.0 license"

[dependencies]
walkdir = "2"
vantara = { path = "../../../" }
