[package]
name = "gzip"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS gzip module"
license = "Apache-2.0 license"

[dependencies]
vantara = { path = "../../../" }
flate2 = "1.0"
