[package]
name = "ls"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS ls module"
license = "Apache-2.0 license"

[dependencies]
chrono = "0.4"
users = "0.11"
vantara = { path = "../../../" }
