[package]
name = "uptime"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS uptime module"
license = "MIT"

[dependencies]
sysinfo = "0.36.1"
chrono = "0.4"
procfs = "0.17.0"
vantara = { path = "../../../" }