[package]
name = "ps"
version = "0.1.0"
edition = "2021"
authors = ["Hafifi"]
description = "Vantara System OS ps module"
license = "MIT"

[dependencies]
users = "0.11"
chrono = "0.4"
procfs = "0.17.0"
rayon = "1.8"
vantara = { path = "../../../" }